taskapp/urls.py
from django.urls import path
from .views import *

app_name='taskapp'

urlpatterns = [
    path('', Home,name='home'),
    path('detail/<int:pk>/', FaylDetail.as_view(),name='detail'),
    path('create', FaylCreateView.as_view(),name='create'),
    path('paylas', PaylasView.as_view(),name='paylas'),
    path('register', RegisterView,name='register'),
    path('login', LoginView.as_view(),name='login'),

    
]

tasks/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskapp.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Fayl(models.Model):
    ad=models.CharField(max_length=264)
    muellif=models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='fayllar')
    fayl=models.FileField(upload_to='documents/%Y/%m/%d',null=True, blank=True)
    aciqlama=models.TextField()

    def __str__(self):
        return str(self.ad)


class Paylas(models.Model):
    kimle=models.ForeignKey(User, on_delete=models.CASCADE, related_name='gore_bildiyi_fayllar')
    fayl=models.ForeignKey(Fayl, on_delete=models.CASCADE, related_name='paylasilan_sexsler')
    serh_yaza_biler=models.BooleanField(default=False)


    def __str__(self):
        return str(self.fayl) + ' shared with ' + str(self.kimle)
    class Meta:
        unique_together=['kimle', 'fayl']

class Serh(models.Model):
    fayl=models.ForeignKey(Fayl, on_delete=models.CASCADE, related_name='serhler')
    komment=models.TextField()
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='serh')

    def __str__(self):
        return str(self.user)+' to "'+str(self.fayl)+'": '+str(self.komment)

taskapp/forms.py
from django import forms
from django.db import models
from .models import Fayl
from django.contrib.auth.models import User

class FaylForm(forms.ModelForm):
    muellif=forms.CharField(widget = forms.HiddenInput(), required=False)

    class Meta:
        model=Fayl
        fields=['ad', 'fayl', 'aciqlama']
        labels = {
            "aciqlama": "Açıqlama"
        }
    def save(self, commit=True, user=None):
        obj = super().save(commit=False) # here the object is not commited in db
        obj.muellif = user
        obj.save()
        return obj

taskapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, request
from django.urls import reverse
from .models import Fayl, Paylas, Serh
from .forms import FaylForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.http import JsonResponse
from django import forms
from django.forms.utils import ErrorList
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.shortcuts import resolve_url
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect



class LoginView(auth_views.LoginView):
    template_name = 'auth/login.html'

    def get_success_url(self):
        return resolve_url('taskapp:home')

def RegisterView(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('taskapp:login')
    else:
        form = UserCreationForm()
    return render(request, 'auth/user_form.html', {'form': form})

@login_required(login_url='/login')
def Home(request):
    if request.method == 'POST':
        form = FaylForm(request.POST, request.FILES)
        if form.is_valid():
            res=form.save(commit=True, user=request.user)
            Paylas.objects.create(kimle=request.user, fayl=res,serh_yaza_biler=True)
            return HttpResponseRedirect(reverse('taskapp:detail', kwargs={'pk': res.id}))
    else:
        form = FaylForm()

    Fayls = Fayl.objects.all()

    return render(request,
        'taskapp/home.html',
        {'Fayls': Fayls, 'form': form},
    )




class FaylDetail(DetailView):

    model = Fayl

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        gore_biler=Paylas.objects.filter(kimle=self.request.user, fayl=context['fayl'])

        if gore_biler:
            if context['fayl'].muellif==self.request.user:
                context['muellifdir']=True
                context['userler']=User.objects.all()
            context['yaza_biler']=gore_biler[0].serh_yaza_biler
            return context


class FaylCreateView(CreateView):
    model = Serh
    fields = ['fayl', 'komment']

    def form_valid(self, form):
        serh=form.save(commit=False)
        serh.user=self.request.user
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request, *args, **kwargs):
        yaza_biler=Paylas.objects.filter(kimle=self.request.user, fayl=request.POST['fayl'])[0].serh_yaza_biler
        if not yaza_biler:
            return HttpResponse('Serh yaza bilmezsiniz')
        self.object = None
        return super().post(request, *args, **kwargs)


    def get_success_url(self):
        return reverse('taskapp:detail', kwargs={'pk': self.object.fayl.pk})



class PaylasView(CreateView):
    model = Paylas
    fields = ['kimle', 'fayl', 'serh_yaza_biler']

    def post(self, request, *args, **kwargs):
        curr_fayl=Fayl.objects.filter(id=request.POST['fayl'])[0]
        if not curr_fayl.muellif==request.user:
            return HttpResponse('Siz muellif deyilsiniz')
        self.object = None
        return super().post(request, *args, **kwargs)



    def get_success_url(self):
        return reverse('taskapp:detail', kwargs={'pk': self.object.fayl.pk})

taskapp/templates/taskapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%block content%}
    {%endblock%}
</body>
</html>

taskapp/templates/taskapp/fayl_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'taskapp:home' %}">Home</a>
{% if object %}
{% include 'taskapp/detail_style.html' %}





<div id="page-wrapper">




    
      <div class="parallax">
          <section id="hero">
          <h2>
           Faylın adı: {{object.ad}}
          </h2>
          <div id="aciqlama" class="parts">Müəllif: {{object.muellif}}</div>
              <div class="parts"><a id="download"  href="/{{object.fayl}}">Faylı Yüklə</a></div>
              <div id="aciqlama" class="parts">Açıqlama: {{object.aciqlama}}</div>

      </section>
      </div>
      
      
  </div>



    <div>
<br>
<br>
<hr>
{% if muellifdir %}


<form style="display: flex; width: fit-content; margin: auto;" action="{% url 'taskapp:paylas' %}" method="post">
    {% csrf_token %}
    <label for="kimle">İstifadəçi seç:</label>
<select name="kimle" id="">
{% for usr in userler %}
    <option value="{{usr.id}}">{{usr.username}}</option>
{% endfor %}
</select>
<input type="hidden" name="fayl" value={{object.id}}>
<p><label for="id_serh_yaza_biler">Bu şəxs şərh yaza bilər:</label> <input type="checkbox" name="serh_yaza_biler" id="id_serh_yaza_biler"></p>
<input type="submit" value="Bu Şəxslə Paylaş">
</form>

{%endif%}

<hr>
    {% include "taskapp/style_komment.html" %}

    <div class="comments-container">
        <h1>Kommentlər </h1>
    
        <ul id="comments-list" class="comments-list">

            {% if yaza_biler %}



<li>            <form action="{% url 'taskapp:create'%}" method="post">
    {%csrf_token%}
    <input type="hidden" name="fayl" value="{{object.id}}">
    <div>
    <textarea  name="komment" id="comments" style="font-family:sans-serif;font-size:1.2em; width:100%;" placeholder="Komment Yaz..."></textarea>
    </div>
    <input type="submit" value="Kommenti Paylaş">
    </form></li>
            
            {%else%}
            Yalniz oxumaq mumkundur
                {%endif%}


{%for serh in object.serhler.all%}











        <li>
            <div class="comment-main-level">

                <div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_1_zps8e1c80cd.jpg" alt=""></div>
  
                <div class="comment-box">
                    <div class="comment-head">
                        <h6 class="comment-name">{{serh.user}}</h6>
                        
                        <i class="fa fa-reply"></i>
                        <i class="fa fa-heart"></i>
                    </div>
                    <div class="comment-content">
                        {{serh.komment}}
                    </div>
                </div>
            </div>

        </li>














{% endfor %}
</ul>
</div>

    </div>



{%else%}
Fayl yoxdur ve ya muellif bu fayli sizinle paylasmayib

{%endif%}













</body>
</html>

taskapp/templates/taskapp/home.html
{% extends "taskapp/base.html" %}
{%block content%}






    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <style>
      html, body {
      min-height: 100%;
      }
      body, div, form, input, select, textarea, p { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      line-height: 22px;
      }
      h1 {
      position: relative;
      margin: 0;
      font-size: 32px;
      color: #fff;
      z-index: 2;
      }
      .testbox {
      display: flex;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 20px;
      }
      form {
      width: 100%;
      padding: 20px;
      border-radius: 6px;
      background: #fff;
      box-shadow: 0 0 30px 0 #8ebf42; 
      }
      .banner {
      position: relative;
      height: 210px;
      background-image: url("/uploads/media/default/0001/01/a3df023f124a8bec3b213347404fe0a7318161de.jpeg");  
      background-size: cover;
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
      }
      .banner::after {
      content: "";
      background-color: rgba(0, 0, 0, 0.5); 
      position: absolute;
      width: 100%;
      height: 100%;
      }
      p.top-info {
      margin: 10px 0;
      }
      input, select, textarea {
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 3px;
      }
      input {
      width: calc(100% - 10px);
      padding: 5px;
      }
      select {
      width: 100%;
      padding: 7px 0;
      background: transparent;
      }
      textarea {
      width: calc(100% - 12px);
      padding: 5px;
      }
      .item:hover p, .item:hover i, .question:hover p, .question label:hover, input:hover::placeholder {
      color: #8ebf42;
      }
      .item input:hover, .item select:hover, .item textarea:hover {
      border: 1px solid transparent;
      box-shadow: 0 0 8px 0 #8ebf42;
      color: #8ebf42;
      }
      .item {
      position: relative;
      margin: 10px 0;
      }
      input[type="date"]::-webkit-inner-spin-button {
      display: none;
      }
      .item i, input[type="date"]::-webkit-calendar-picker-indicator {
      position: absolute;
      font-size: 20px;
      color: #a9a9a9;
      }
      .item i {
      right: 2%;
      top: 30px;
      z-index: 1;
      }
      [type="date"]::-webkit-calendar-picker-indicator {
      right: 1%;
      z-index: 2;
      opacity: 0;
      cursor: pointer;
      }
      input[type=radio] {
      width: 0;
      visibility: hidden;
      }
      label.radio {
      position: relative;
      display: inline-block;
      margin: 5px 20px 25px 0;
      cursor: pointer;
      }
      .question span {
      margin-left: 30px;
      }
      label.radio:before {
      content: "";
      position: absolute;
      left: 0;
      width: 17px;
      height: 17px;
      border-radius: 50%;
      border: 2px solid #8ebf42;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 8px;
      height: 4px;
      top: 6px;
      left: 5px;
      background: transparent;
      border: 3px solid #8ebf42;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 150px;
      padding: 10px;
      border: none;
      border-radius: 5px; 
      background: #8ebf42;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }
      button:hover {
      background: #82b534;
      }
      @media (min-width: 568px) {
      .name-item, .city-item {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      }
      .name-item input, .city-item input {
      width: calc(50% - 20px);
      }
      .city-item select {
      width: calc(50% - 8px);
      }
      }
      h4{
            margin: 0 8px;
            cursor:pointer
      }
      svg{
        cursor: pointer;
      }
      .file{
        z-index: 5;
      }
      a{
        text-decoration: none;
      }
      .bannin {
    display: flex;
    width: 90%;
    margin: auto;
    align-items: center;
    justify-content: space-evenly;
    flex-wrap: wrap;
}
    </style>
    <div class="testbox">


    <form action="{% url 'taskapp:home' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
<div class="banner">
<div class="bannin">
  <h1>Fayl Paylaşma Applikasiyası</h1>

  {% for each in Fayls %}
  
  <a class="file" href="{% url 'taskapp:detail' each.id %}">
    <div>
      <h4>{{each}}</h4>
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="50px" width="50px" fill="#000000" version="1.1" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve"><path d="M62.448,5H15v90h69.231V26.783L62.448,5z M63.462,10.909l14.86,14.86h-14.86V10.909z M18.462,91.538V8.462H60v20.769h20.769  v62.308H18.462z"></path><rect x="28.846" y="50" width="41.538" height="1.731"></rect><rect x="28.846" y="77.692" width="41.538" height="1.731"></rect><rect x="28.846" y="56.923" width="13.846" height="1.731"></rect><rect x="28.846" y="43.077" width="41.538" height="1.731"></rect><rect x="28.846" y="36.154" width="41.538" height="1.731"></rect><rect x="28.846" y="29.231" width="24.231" height="1.731"></rect><rect x="28.846" y="63.846" width="13.846" height="1.731"></rect><rect x="49.616" y="60.385" width="1.731" height="8.654"></rect><rect x="66.923" y="60.385" width="1.731" height="8.654"></rect><rect x="28.846" y="70.769" width="13.846" height="1.731"></rect><path d="M47.885,56.923v5.192h5.192v-5.192H47.885z M51.346,60.385h-1.731v-1.731h1.731V60.385z"></path><path d="M47.885,67.308V72.5h5.192v-5.192H47.885z M51.346,70.769h-1.731v-1.731h1.731V70.769z"></path><path d="M65.192,67.308V72.5h5.192v-5.192H65.192z M68.654,70.769h-1.731v-1.731h1.731V70.769z"></path><path d="M65.192,56.923v5.192h5.192v-5.192H65.192z M68.654,60.385h-1.731v-1.731h1.731V60.385z"></path><rect x="51.346" y="58.654" width="15.577" height="1.731"></rect><rect x="51.346" y="69.038" width="15.577" height="1.731"></rect></svg></div>
  
  
  
  
  </a>
  {% endfor %}

</div>

        </div>
        
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.label_tag }} {{ form.help_text }}</p>
        <p>
            {{ form.errors }}
            {{ form }}
        </p>
         <div class="btn-block">
          <button type="submit" >Paylas</button>
        </div>
    </form>




    </div>



{%endblock%}

taskapp/templates/taskapp/paylas_form.html
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

taskapp/templates/taskapp/serh_form.html
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

taskapp/templates/taskapp/style_komment.html
<style>
/**
 * Oscuro: #283035
 * Azul: #03658c
 * Detalle: #c7cacb
 * Fondo: #dee1e3
 ----------------------------------*/
 * {
 	margin: 0;
 	padding: 0;
 	-webkit-box-sizing: border-box;
 	-moz-box-sizing: border-box;
 	box-sizing: border-box;
 }

 a {
 	color: #03658c;
 	text-decoration: none;
 }

ul {
	list-style-type: none;
}

body {
	font-family: 'Roboto', Arial, Helvetica, Sans-serif, Verdana;
	background: #dee1e3;
}

/** ====================
 * Lista de Comentarios
 =======================*/
.comments-container {
	margin: 60px auto 15px;
	width: 768px;
}

.comments-container h1 {
	font-size: 36px;
	color: #283035;
	font-weight: 400;
}

.comments-container h1 a {
	font-size: 18px;
	font-weight: 700;
}

.comments-list {
	margin-top: 30px;
	position: relative;
}

/**
 * Lineas / Detalles
 -----------------------*/
.comments-list:before {
	content: '';
	width: 2px;
	height: 100%;
	background: #c7cacb;
	position: absolute;
	left: 32px;
	top: 0;
}



.reply-list:before, .reply-list:after {display: none;}
.reply-list li:before {
	content: '';
	width: 60px;
	height: 2px;
	background: #c7cacb;
	position: absolute;
	top: 25px;
	left: -55px;
}


.comments-list li {
	margin-bottom: 15px;
	display: block;
	position: relative;
}

.comments-list li:after {
	content: '';
	display: block;
	clear: both;
	height: 0;
	width: 0;
}

.reply-list {
	padding-left: 88px;
	clear: both;
	margin-top: 15px;
}
/**
 * Avatar
 ---------------------------*/
.comments-list .comment-avatar {
	width: 65px;
	height: 65px;
	position: relative;
	z-index: 99;
	float: left;
	border: 3px solid #FFF;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
	-webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.2);
	-moz-box-shadow: 0 1px 2px rgba(0,0,0,0.2);
	box-shadow: 0 1px 2px rgba(0,0,0,0.2);
	overflow: hidden;
}

.comments-list .comment-avatar img {
	width: 100%;
	height: 100%;
}

.reply-list .comment-avatar {
	width: 50px;
	height: 50px;
}

.comment-main-level:after {
	content: '';
	width: 0;
	height: 0;
	display: block;
	clear: both;
}
/**
 * Caja del Comentario
 ---------------------------*/
.comments-list .comment-box {
	width: 680px;
	float: right;
	position: relative;
	-webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.15);
	-moz-box-shadow: 0 1px 1px rgba(0,0,0,0.15);
	box-shadow: 0 1px 1px rgba(0,0,0,0.15);
}

.comments-list .comment-box:before, .comments-list .comment-box:after {
	content: '';
	height: 0;
	width: 0;
	position: absolute;
	display: block;
	border-width: 10px 12px 10px 0;
	border-style: solid;
	border-color: transparent #FCFCFC;
	top: 8px;
	left: -11px;
}

.comments-list .comment-box:before {
	border-width: 11px 13px 11px 0;
	border-color: transparent rgba(0,0,0,0.05);
	left: -12px;
}

.reply-list .comment-box {
	width: 610px;
}
.comment-box .comment-head {
	background: #FCFCFC;
	padding: 10px 12px;
	border-bottom: 1px solid #E5E5E5;
	overflow: hidden;
	-webkit-border-radius: 4px 4px 0 0;
	-moz-border-radius: 4px 4px 0 0;
	border-radius: 4px 4px 0 0;
}

.comment-box .comment-head i {
	float: right;
	margin-left: 14px;
	position: relative;
	top: 2px;
	color: #A6A6A6;
	cursor: pointer;
	-webkit-transition: color 0.3s ease;
	-o-transition: color 0.3s ease;
	transition: color 0.3s ease;
}

.comment-box .comment-head i:hover {
	color: #03658c;
}

.comment-box .comment-name {
	color: #283035;
	font-size: 14px;
	font-weight: 700;
	float: left;
	margin-right: 10px;
}

.comment-box .comment-name a {
	color: #283035;
}

.comment-box .comment-head span {
	float: left;
	color: #999;
	font-size: 13px;
	position: relative;
	top: 1px;
}

.comment-box .comment-content {
	background: #FFF;
	padding: 12px;
	font-size: 15px;
	color: #595959;
	-webkit-border-radius: 0 0 4px 4px;
	-moz-border-radius: 0 0 4px 4px;
	border-radius: 0 0 4px 4px;
}

.comment-box .comment-name.by-author, .comment-box .comment-name.by-author a {color: #03658c;}
.comment-box .comment-name.by-author:after {
	content: 'autor';
	background: #03658c;
	color: #FFF;
	font-size: 12px;
	padding: 3px 5px;
	font-weight: 700;
	margin-left: 10px;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
}

@media only screen and (max-width: 766px) {
	.comments-container {
		width: 480px;
	}

	.comments-list .comment-box {
		width: 390px;
	}

	.reply-list .comment-box {
		width: 320px;
	}
}

</style>